version: '3.3'
services:
  db:
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - 'data:/data/db'
    image: mongo
  auth:
    container_name: auth
    build: 
      context: ./
      dockerfile: ./auth/Dockerfile
    ports: 
      - "9010:9010"
    image: auth
    depends_on:
      - db
    environment:
      - spring.data.mongodb.uri=mongodb://mongoadmin:mongoadmin@db:27017/authservice?authSource=admin
  post:
    container_name: post
    build:
      context: ./
      dockerfile: ./post/Dockerfile
    ports: 
      - "9020:9020"
    image: post
    depends_on:
      - db
    environment:
      - spring.data.mongodb.uri=mongodb://mongoadmin:mongoadmin@db:27017/postservice?authSource=admin
  geo:
    container_name: geo
    build:
      context: ./
      dockerfile: ./geo/Dockerfile
    ports: 
      - "9000:9000"
    image: geo
    depends_on:
      - db
    environment:
      - spring.data.mongodb.uri=mongodb://mongoadmin:mongoadmin@db:27017/geoservice?authSource=admin
  ui:
    container_name: ui
    build: ./web-ui
    ports:
      - "4200:4200"
    image: ui
    depends_on:
      - auth
      - post
      - geo

volumes: 
  data: