export const ACCESS_TOKEN_KEY = 'access_token'
export const REFRESH_TOKEN_KEY = 'refresh_token'
export const USER_NAME_KEY = 'user'
export const PASSWORD_KEY = 'pwd'
export const CLIENT_ID = 'client_id'
