apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: geo
  name: geo
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: geo
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: geo
    spec:
      containers:
        - env:
            - name: spring.data.mongodb.uri
              value: mongodb://mongoadmin:mongoadmin@db:27017/geoservice?authSource=admin
          image: geo
          name: geo
          imagePullPolicy: Never
          ports:
            - containerPort: 9000
          resources: {}
      restartPolicy: Always
status: {}
