apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: post
  name: post
spec:
  ports:
    - name: "9020"
      port: 9020
      targetPort: 9020
  selector:
    io.kompose.service: post
status:
  loadBalancer: {}
