apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: post
  name: post
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: post
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: post
    spec:
      containers:
        - env:
            - name: spring.data.mongodb.uri
              value: mongodb://mongoadmin:mongoadmin@db:27017/postservice?authSource=admin
          image: post
          name: post
          imagePullPolicy: Never
          ports:
            - containerPort: 9020
          resources: {}
      restartPolicy: Always
status: {}
